config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }


  resources :users do
	   resources :posts
  end
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user, foreign_key: :author_id
    mount_uploader :thumbnail, ThumbnailUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, foreign_key: :author_id
	validates :email, presence: true

	def full_name
		"#{first_name.capitalize} #{last_name.capitalize}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_user
	before_action :load_post, only: [:show, :edit, :update, :destroy]

	def index
    if @user
		    @posts = @user.posts
    else
        @posts = Post.all.order('title ASC')
    end
	end

	def show

	end

	def load_post
		@post = Post.find params[:id]
	end

	def load_user
    if params[:user_id].present?
  		@user = User.find params[:user_id]
    end
	end

	def edit

	end

	def update
		if @post.update_attributes post_params
			redirect_to [@user, @post]
		else
			render 'edit'
		end
	end

	def new
		@post = Post.new
	end

	def destroy
		@post.destroy
		if @post.save
			redirect_to @user
		end
	end

	def create
		@post = Post.new(post_params)
		@post.user = @user
		if @post.save
			redirect_to [@user, @post]
		else
			render 'new'
		end
	end

	private

    def post_params
    # Définit les attributs autorisés et les prend en compte
      params.require(:post).permit(
		:title,
		:thumbnail,
		:author_id
		)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
   end

   # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
 end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def load_user
		@user = User.find params[:id]
	end

  def index
		@users = User.all.order('first_name ASC')
	end

	def show

	end

	def edit

	end

	def update
		if @user.update_attributes user_params
			redirect_to @user
		else
			render 'edit'
		end
	end

	def new

	end

	def destroy
    puts "destroy"
		@user.destroy
		if @user.save
			redirect_to @user
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	private

    def user_params
    # Définit les attributs autorisés et les prend en compte
      params.require(:user).permit(
		:first_name,
		:last_name,
		:email
		)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="  https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :thumbnail %>
	<%= f.file_field :thumbnail %>
	<%= f.label :author_id %>
	<%= f.number_field :author_id %>

	<%= f.submit %>
</div>

app/views/posts/edit.html.erb
<%= form_for [@user, @post] do |f| %>
	<%= render partial: "form", locals: { f: f } %>
<% end %>

<%= link_to 'Cancel', [@user, @post], class: "btn btn-primary" %>

app/views/posts/index.html.erb
<h2>
	Post List
</h2>

<% if @user.present? %>
	<%= link_to 'Add Post', new_user_post_path(), class: "btn btn-primary" %>
<% end %>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %>
<% end %>

<ul>
<%-@posts.each do |post| link_to %>

<% if @user.present? %>
	<%= link_to user_post_path(@user, post) do %>
		<li>
			<%= post.title %>
			<ul>
				<li><img src="<%= post.thumbnail.thumb.url %>"></img></li>
				<li><%= post.author_id %></li>
			</ul>
		</li>
	<% end %>

<% else %>
		<%= link_to post_path(post) do %>
			<li>
				<%= post.title %>
				<ul>
					<li><img src="<%= post.thumbnail.thumb.url %>"></img></li>
					<li><%= post.author_id %></li>
				</ul>
			</li>
		<% end %>
	<% end %>
	<br/>
<% end %>

</ul>

app/views/posts/new.html.erb
<%= form_for [@user, @post] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :header %>
	<%= f.text_field :header %>
	<%= f.label :thumbnail %>
	<%= f.file_field :thumbnail %>
	<%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<% if @user.present? %>
	<%= link_to 'Back to user', [@user], class:"btn btn-primary" %>
<% end %>
<br/>
<%= @post.title %>
<ul>
	<li><img src="<%= @post.thumbnail.thumb.url %>"></img></li>
	<li><%= @post.author_id %></li>
</ul>

<% if @user.present? %>
	<%= link_to 'Edit', edit_user_post_path, class:"btn btn-warning" %>
	<%= link_to 'Delete', user_post_path, method: :delete, data:{confirm:"Are you sure ?"}, class:"btn btn-danger" %>

	<h3>User</h3>
	<%= @user.first_name %> <%= @user.last_name %>
<% else %>
	<%= link_to 'Edit', edit_post_path, class:"btn btn-warning" %>
	<%= link_to 'Delete', post_path, method: :delete, data:{confirm:"Are you sure ?"}, class:"btn btn-danger" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
		<%- if @user.errors[:email].present? %>
			<%= @user.errors[:email].to_sentence %>
		<% end %>

		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= f.submit class:"btn btn-primary" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

<%= link_to 'Cancel', user_path(@user), class: "btn btn-primary" %>

app/views/users/index.html.erb
<h2>
	Users List
</h2>


<%= link_to 'Add User', new_user_path(), class: "btn btn-primary" %>


<ul>
<%-@users.each do |user| link_to %>
		<%= link_to user_path(user) do %>
			<li>
			<%= user.full_name %>
				<ul>
					<li><%= user.email %></li>
				</ul>
			</li>
		<% end %>
	<br/>
<% end %>
</ul>

app/views/users/new.html.erb
<%= form_for User.new do |f| %>
	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= f.submit class:"btn btn-primary" %>
	</div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= link_to "All users", :users, class:"btn btn-primary"%>
<br/>
<%= @user.full_name %>
<ul>
	<li><%= @user.email %></li>
</ul>


<h3>Posts</h3>

<ul>
<% @user.posts.each do |p| %>
	<li>
		<%= link_to [@user, p] do %>
			<%= p.title %>
		<% end %>
	</li>
<% end %>
</ul>

<%= link_to 'Posts', user_posts_path(@user), class:"btn btn-primary" %>
<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-warning" %>
<%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm:"Are you sure ?"}, class:"btn btn-danger" %>